import React, {useState, useEffect, useRef} from 'react';
import styles from './ModifyLibrat.module.css';
import { GetLibrat, updateBook, searchBook, searchBookSpecial } from '../../server/server';

const ModifyLibrat = () => {
  const [limit, setLimit] = useState(7);
  const [librat, setLibrat] = useState([]);
  const [oneLiber, setOneLiber] = useState({});
  const [categories, setCategories] = useState([])
  const searchinput = useRef(null);
  const chosenCategory = useRef(null)
  const chosenSort = useRef(null);

  const [popupStat, setPopupStat] = useState(false);
  const box = useRef(null);

  //these are for the edit
  const titulli = useRef(null);
  const rafti = useRef(null);
  const rreshti = useRef(null);
  const kategoria = useRef(null);
  const autori = useRef(null);
  const stocku = useRef(null);

  useEffect(() => {
    let kategorite = [];
    let unique;
    GetLibrat().then((res)=> {
      setLibrat(res.result)
      let librat = res.result;
  
      librat.forEach((liber)=>{
        kategorite.push(liber.category)
      })
      unique = [...new Set(kategorite)];
  
      setCategories(unique);
    })
  }, [])
  

  useEffect(() => {
  }, [popupStat]);
  
  const moreList = () => {
    if (librat.length > limit) {
      setLimit(limit + 7);
      
    }
  };

  const bookClickHandle = (id) => {
    librat.map((liber) => liber.isbn === id && setOneLiber(liber));
    setPopupStat(true);
  };

  const goOut = (e) => {
    if (e.target.firstChild === box.current) {
      setPopupStat(false);
    }
  };

  const kerko = () => {
    const toSearch = searchinput.current.value;
    const catoption = chosenCategory.current.value;
    const sortOption = chosenSort.current.value; 
    if(toSearch === "" && catoption === "All" && sortOption === "normal"){
      GetLibrat().then((res)=> {
        setLibrat(res.result)
      })
    }else{
      if(catoption === "All"){
        searchBookSpecial(toSearch, sortOption).then((res)=>{
          setLibrat(res.resu);

        })
      }else{
        searchBook(toSearch, catoption, sortOption).then((res)=> {
          setLibrat(res.resu);
        })
      }
    }
  }
  const handleEditSubmit = () => {
    const liberObj = {
      title: titulli.current.value,
      shelf: rafti.current.value,
      row: parseInt(rreshti.current.value),
      category: kategoria.current.value,
      author: autori.current.value,
      stock: parseInt(stocku.current.value),
      isbn: oneLiber.isbn,
    };

    updateBook(liberObj);
    setPopupStat(false);
  };

  if(librat === []){
    return(
      <div>loading</div>
    );
  }else{
    return (
      <div>
        <head>
          <title>Alert Page - Xtreme Starter Next Js App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </head>
        <div>
          <p className={styles.title}>Lista e librave</p>
          <div className={styles.searchBar}>
            <input
              className={styles.input}
              type="text"
              placeholder="Search for a book"
              ref={searchinput}
            />
            <label className={styles.label} htmlFor="kategoria">
              Kategoria
            </label>
            <select ref={chosenCategory} className={styles.select} name="kategoria" id="">
              <option value="All">All</option>
              {categories.map((uniq, i) => (
                <option key={i} value={uniq}>{uniq}</option>
              ))}
            </select>
  
            <label className={styles.label} htmlFor="listo">
              Listo sipas
            </label>
            <select ref={chosenSort}className={styles.select} name="listo" id="">
              <option value="emri_A_Z">Emri A-Z</option>
              <option value="normal">Normal</option>
              <option value="stoku">Stoku</option>
            </select>
            <br />
            <div onClick={kerko} className={styles.btn}>Kerko</div>
          </div>
          {/* book list */}
          <div>
            {librat.map(
              (liber, i) =>
                i < limit && (
                  <div onClick={()=>bookClickHandle(liber.isbn)} key={i} className={styles.bookItem}>
                    <div className={styles.itemInfo}>
                      <p>Titulli: {liber.title}</p>
                      <p>Autori: {liber.author}</p>
                      <p>Kategoria: {liber.category}</p>
                    </div>
                    <div className={styles.itemSituation}>
                      <p>
                        Statusi:{" "}
                        {liber.status ? "Aktiv" : "Ska ne stok"}
                      </p>
                      <p>Stoku: {liber.stock}</p>
                      <p>ID: {liber.isbn}</p>
                    </div>
                  </div>
                )
            )}
            <div onClick={moreList} className={styles.loadMore}>
              <p>Listo me shume Libra</p>
            </div>
          </div>
  
          {/* list end */}
          
        </div>
        {popupStat && (
            <div onClick={goOut} className={styles.popUp}>
              <div ref={box} className={styles.popupThing}>
                <p className={styles.title}>Modifiko librin 1001</p>
                <input
                  ref={titulli}
                  className={styles.input}
                  type="text"
                  placeholder="Title"
                  defaultValue={oneLiber.title}
                />
                <input
                  ref={rafti}
                  className={styles.input}
                  type="text"
                  placeholder="Rafti"
                  defaultValue={oneLiber.shelf}
                />
                <input
                  ref={rreshti}
                  className={styles.input}
                  type="text"
                  placeholder="Rreshti"
                  defaultValue={oneLiber.row}
                />
                <input
                  ref={kategoria}
                  className={styles.input}
                  type="text"
                  placeholder="Kategoria"
                  defaultValue={oneLiber.category}
                />
                <input
                  ref={autori}
                  className={styles.input}
                  type="text"
                  placeholder="Autori"
                  defaultValue={oneLiber.author}
                />
                <input
                  ref={stocku}
                  className={styles.input}
                  type="text"
                  placeholder="Stocku"
                  defaultValue={oneLiber.stock}
                />
                <div onClick={handleEditSubmit} className={styles.btn}>
                  Edit
                </div>
              </div>
            </div>
        )}
      </div>
    )
  }
}

export default ModifyLibrat;