import React, {useRef} from 'react';
import styles from './CreateLiber.module.css';
import { krijoLiber } from '../../server/server';

const CreateLiber = () => {

  const autori = useRef(null);
  const bookId = useRef(null);
  const kategoria = useRef(null);
  const rafti = useRef(null);
  const rreshti = useRef(null);
  const slug = useRef(null);
  const statusLibriOne = useRef(null);
  const stocku = useRef(null);
  const titulli = useRef(null);

  let statusLibri = true;

  const handleCommentSubmission = () => {
    if (statusLibriOne.current.value === "aktiv") {
      statusLibri = true;
    } else {
      statusLibri = false;
    }

    const bookObj = {
      autori: autori.current.value,
      bookId: parseInt(bookId.current.value),
      kategoria: kategoria.current.value,
      rafti: rafti.current.value,
      rreshti: parseInt(rreshti.current.value),
      slug: slug.current.value,
      statusLibri: statusLibri,
      stocku: parseInt(stocku.current.value),
      titulli: titulli.current.value,
    };

    krijoLiber(bookObj);

    autori.current.value = "";
    bookId.current.value = "";
    kategoria.current.value = "";
    rafti.current.value = "";
    rreshti.current.value = "";
    slug.current.value = "";
    statusLibriOne.current.value = "aktiv";
    stocku.current.value = "";
    titulli.current.value = "";
  };

  return (
    <div>
      <head>
        <title>Xtreme Starter Next Js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <div>
        <p className={styles.title}>Krijo nje liber</p>
        <input
          ref={titulli}
          className={styles.input}
          type="text"
          placeholder="Titulli i librit"
        />
        <input ref={rafti} className={styles.input} type="text" placeholder="Rafti" />
        <input
          ref={rreshti}
          className={styles.input}
          type="text"
          placeholder="Rreshti"
        />
        <input
          ref={kategoria}
          className={styles.input}
          type="text"
          placeholder="Kategoria"
        />
        <input
          ref={bookId}
          className={styles.input}
          type="text"
          placeholder="ID e librit"
        />
        <input ref={slug} className={styles.input} type="text" placeholder="Slug" />
        <label className={styles.label} htmlFor="status">
          Statusi
        </label>
        <select ref={statusLibriOne} className={styles.select} name="status" id="">
          <option value="aktiv">aktiv</option>
          <option value="i huazuar">i huazuar</option>
        </select>
        <input
          ref={autori}
          className={styles.input}
          type="text"
          placeholder="Autori"
        />
        <input ref={stocku} className={styles.input} type="text" placeholder="Stoku" />
        <div onClick={handleCommentSubmission} className={styles.btn}>
          Krijo
        </div>
      </div>
    </div>
  )
}

export default CreateLiber;